name: flutter_authorize_net_client
description: A Simple Flutter plugin to use Authorize.net using it's API.
version: 0.1.0+2
homepage: https://github.com/GAM3RG33K/flutter_authorize_net_client
repository: https://github.com/GAM3RG33K/flutter_authorize_net_client

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # for HTTP requests
  http: ^0.13.3
  # do not change version before implementing null-safety
  # for data model to/from json conversion
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # do not change version before implementing null-safety
  build_runner: ^2.0.4
  # do not change version before implementing null-safety
  json_serializable: ^4.1.3


flutter:
